const urls={
    "Leads":{
        "Create":{
            "URL":"",
            "Code":"",
            "method":"post",
            "DependentAPI":[],
            "SchemaPassed":[]
        },
        "Retreive":{
            "URL":"",
            "Code":"",
            "method":"get",
            "DependentAPI":[],
            "SchemaPassed":[]
        }
    },
    "Activities":{
        "Create":{
            "URL":"",
            "Code":"",
            "method":"post",
            "DependentAPI":[],
            "SchemaPassed":[]
        },
        "Retreive":{
            "URL":"",
            "Code":"",
            "method":"get",
            "DependentAPI":[],
            "SchemaPassed":[]
        }
    },
    "Tasks":{
        "Create":{
            "URL":"",
            "Code":"",
            "method":"post",
            "DependentAPI":[],
            "SchemaPassed":[]
        },
        "Retreive":{
            "URL":"",
            "Code":"",
            "method":"get",
            "DependentAPI":[],
            "SchemaPassed":[]
        }
    },
    "Users":{
        "Create":{
            "URL":"",
            "Code":"",
            "method":"post",
            "DependentAPI":[],
            "SchemaPassed":[]
        },
        "Retreive":{
            "URL":"",
            "Code":"",
            "method":"get",
            "DependentAPI":[],
            "SchemaPassed":[]
        }
    }
}